name: Code Quality Metrics

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper git operations
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install cloc
        run: sudo apt-get install -y cloc
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install code-metrics-tracker==0.1.8
      
      - name: Generate code quality snapshot
        run: codeqa snapshot --only-on-changes
      
      - name: Commit updated CODE_METRICS.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update code quality metrics via GitHub Actions"
          file_pattern: "CODE_METRICS.md generated/metrics/*"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions <actions@github.com>"